version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Determine the jobs to run
          command: OUTPUT_PATH=/tmp/workspace .circleci/scripts/diff.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pipeline-parameters.json

  rust:
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - continuation/continue:
          configuration_path: .circleci/rust.yml
          parameters: /tmp/workspace/pipeline-parameters.json

  chrome-extension:
    executor: continuation/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - continuation/continue:
          configuration_path: .circleci/chrome_extension.yml
          parameters: /tmp/workspace/pipeline-parameters.json

workflows:
  build:
    jobs:
      - setup
      - chrome-extension:
          requires:
            - setup
      # - rust:
      #     requires:
      #       - setup
